[versions]
detekt = "1.23.4"
dokka = "1.9.10"
kotest = "5.8.0"
kotlin = "1.9.21"
kotlinxBinaryCompatibilityValidator = "0.13.2"
kotlinxSerialization = "1.5.1"
kover = "0.7.5"

[libraries]
kotest-assertionsCore = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-frameworkDatatest = { group = "io.kotest", name = "kotest-framework-datatest", version.ref = "kotest" }
kotest-frameworkEngine = { group = "io.kotest", name = "kotest-framework-engine", version.ref = "kotest" }
kotest-runnerJunit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotest-multiplatform = { id = "io.kotest.multiplatform", version.ref = "kotest" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinxBinaryCompatibilityValidator" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }